---
title: 'Homework #4'
author: "Adam Kiehl"
date: "2022-10-10"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) # dplyr
library(knitr) # kable
library(kableExtra) # extension of kable
library(sparkline) # interactivity
sparkline(0)
```

- Data source
- What you want to convey
- Table functionality
- Table formatting

```{r}
# read in the data from a .csv file
data <- read.csv('players.csv') %>%
  # rename misnamed fields
  rename(PlusMinus = 'X...',
         SPer = 'S.') %>%
  # filter out unneeded data
  filter(Player != '',
         Tm != 'TOT')

head(data)
```


```{r, message=FALSE}
plt_data <- data %>%
  filter(PTS > 5) %>%
  group_by(Tm) %>%
  summarize(PTS = NA, 
            PIM = sum(PIM) / 82,
            EVG = sum(EVG)/ 82,
            EVA = sum(EVA)/ 82,
            PPG = sum(PPG)/ 82,
            PPA = sum(PPA) / 82,
            S = sum(S) / 82,
            SPer = mean(SPer, na.rm = TRUE)) %>%
  as.data.frame()



top3 <- plt_data$PIM %in% (plt_data %>% 
                             arrange(desc(PIM)) %>% 
                             select(PIM) %>% 
                             top_n(3) %>%
                             pull(PIM))
bottom3 <- plt_data$PIM %in% (plt_data %>% 
                                arrange(desc(PIM)) %>% 
                                select(PIM) %>% 
                                top_n(-3) %>%
                                pull(PIM))
neither <- !top3 & !bottom3
plt_data$PIM[top3] <- cell_spec(round(plt_data$PIM[top3], 2), 
                                color = 'green', 
                                bold = TRUE)
plt_data$PIM[bottom3] <- cell_spec(round(as.numeric(plt_data$PIM[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$PIM[neither] <- cell_spec(round(as.numeric(plt_data$PIM[neither]), 2))




top3 <- plt_data$EVG %in% (plt_data %>% 
                             arrange(desc(EVG)) %>% 
                             select(EVG) %>% 
                             top_n(3) %>%
                             pull(EVG))
bottom3 <- plt_data$EVG %in% (plt_data %>% 
                                arrange(desc(EVG)) %>% 
                                select(EVG) %>% 
                                top_n(-3) %>%
                                pull(EVG))
neither <- !top3 & !bottom3
plt_data$EVG[top3] <- cell_spec(round(plt_data$EVG[top3], 2),
                                color = 'green', 
                                bold = TRUE)
plt_data$EVG[bottom3] <- cell_spec(round(as.numeric(plt_data$EVG[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$EVG[neither] <- cell_spec(round(as.numeric(plt_data$EVG[neither]), 2))





top3 <- plt_data$EVA %in% (plt_data %>% 
                             arrange(desc(EVA)) %>% 
                             select(EVA) %>% 
                             top_n(3) %>%
                             pull(EVA))
bottom3 <- plt_data$EVA %in% (plt_data %>% 
                                arrange(desc(EVA)) %>% 
                                select(EVA) %>% 
                                top_n(-3) %>%
                                pull(EVA))
neither <- !top3 & !bottom3
plt_data$EVA[top3] <- cell_spec(round(plt_data$EVA[top3], 2), 
                                color = 'green', 
                                bold = TRUE)
plt_data$EVA[bottom3] <- cell_spec(round(as.numeric(plt_data$EVA[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$EVA[neither] <- cell_spec(round(as.numeric(plt_data$EVA[neither]), 2))






top3 <- plt_data$PPG %in% (plt_data %>% 
                             arrange(desc(PPG)) %>% 
                             select(PPG) %>% 
                             top_n(3) %>%
                             pull(PPG))
bottom3 <- plt_data$PPG %in% (plt_data %>% 
                                arrange(desc(PPG)) %>% 
                                select(PPG) %>% 
                                top_n(-3) %>%
                                pull(PPG))
neither <- !top3 & !bottom3
plt_data$PPG[top3] <- cell_spec(round(plt_data$PPG[top3], 2), 
                                color = 'green', 
                                bold = TRUE)
plt_data$PPG[bottom3] <- cell_spec(round(as.numeric(plt_data$PPG[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$PPG[neither] <- cell_spec(round(as.numeric(plt_data$PPG[neither]), 2))





top3 <- plt_data$PPA %in% (plt_data %>% 
                             arrange(desc(PPA)) %>% 
                             select(PPA) %>% 
                             top_n(3) %>%
                             pull(PPA))
bottom3 <- plt_data$PPA %in% (plt_data %>% 
                                arrange(desc(PPA)) %>% 
                                select(PPA) %>% 
                                top_n(-3) %>%
                                pull(PPA))
neither <- !top3 & !bottom3
plt_data$PPA[top3] <- cell_spec(round(plt_data$PPA[top3], 2), 
                                color = 'green', 
                                bold = TRUE)
plt_data$PPA[bottom3] <- cell_spec(round(as.numeric(plt_data$PPA[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$PPA[neither] <- cell_spec(round(as.numeric(plt_data$PPA[neither]), 2))





top3 <- plt_data$S %in% (plt_data %>% 
                             arrange(desc(S)) %>% 
                             select(S) %>% 
                             top_n(3) %>%
                             pull(S))
bottom3 <- plt_data$S %in% (plt_data %>% 
                                arrange(desc(S)) %>% 
                                select(S) %>% 
                                top_n(-3) %>%
                                pull(S))
neither <- !top3 & !bottom3
plt_data$S[top3] <- cell_spec(round(plt_data$S[top3], 2), 
                                color = 'green', 
                                bold = TRUE)
plt_data$S[bottom3] <- cell_spec(round(as.numeric(plt_data$S[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$S[neither] <- cell_spec(round(as.numeric(plt_data$S[neither]), 2))





top3 <- plt_data$SPer %in% (plt_data %>% 
                             arrange(desc(SPer)) %>% 
                             select(SPer) %>% 
                             top_n(3) %>%
                             pull(SPer))
bottom3 <- plt_data$SPer %in% (plt_data %>% 
                                arrange(desc(SPer)) %>% 
                                select(SPer) %>% 
                                top_n(-3) %>%
                                pull(SPer))
neither <- !top3 & !bottom3
plt_data$SPer[top3] <- cell_spec(round(plt_data$SPer[top3], 2), 
                                color = 'green', 
                                bold = TRUE)
plt_data$SPer[bottom3] <- cell_spec(round(as.numeric(plt_data$SPer[bottom3]), 2), 
                                   color = 'red', 
                                   bold = TRUE)
plt_data$SPer[neither] <- cell_spec(round(as.numeric(plt_data$SPer[neither]), 2))












for (team in plt_data$Tm) {
  team_pts <- data %>%
    filter(Tm == team) %>%
    pull(PTS)

  plt_data$PTS[which(plt_data$Tm == team)] <- spk_chr(team_pts,
                                                      type = 'box',
                                                      chartRangeMin = 0,
                                                      chartRangeMax = max(
                                                        data$PTS),
                                                      width = 150)
}

plt_data %>%
  kbl(escape = FALSE,
      col.names = c('Team', 'Points', 'Penalty Mins', 'Goals', 'Assists', 
                    'Goals', 'Assists', 'Total', 'Percent'),
      align = c('l', 'c', rep('r', 7)),
      digits = 2) %>%
  kable_styling(font_size = 15,
                fixed_thead = TRUE) %>%
  add_header_above(c(rep('', 3), 
                     'Even-Strength' = 2, 
                     'Power-Play' = 2, 
                     'Shooting' = 2)) %>%
  kable_material(lightable_options = c('striped', 'hover'))
```






